### ISSUE TITLE
Sort By User in User Story Section

### ISSUE THREAD

**Issue by AnshumanDhiman** [EOS-uiux-Solutions/user-story#110]
## Is your feature request related to a problem? Please describe.

If a user wants to watch all the stories from a particular user, he cannot access them from the main page. Rather the user has to visit the profile to view them.

## Describe the solution you'd like

A Sort By User can be added in the (Sort by) section which sorts by the users in the story.

## Additional context
This is the current Sort by in the user story.
![3](https://user-images.githubusercontent.com/67755381/146683600-ab0a2430-4cdf-4c90-9b08-ff3e52ce8804.jpg)
After addition of the Sort by feature to the user story.
![idea](https://user-images.githubusercontent.com/67755381/146683601-df961146-82d0-4962-a3c3-f09673dce71c.jpg)

**Comment by AnshumanDhiman** [comment]
Can I work on this if it is good to go ? @cyntss @sharmaaditya570191

**Comment by SundeepChand** [comment]
Hi @AnshumanDhiman, this feature has been implemented in the search (the dropdown has the option of searching by story title or story author). So I'm closing this issue. Feel free to suggest any other improvements to the existing functionality : )

![1](https://user-images.githubusercontent.com/34120932/152582005-09dd6754-4185-4175-92cb-4561c8b41722.PNG)
