### ISSUE TITLE
Change Reply button position 

### ISSUE THREAD

**Issue by codetheorem** [EOS-uiux-Solutions/user-story#122]
## Describe the bug

The reply button and View replies button are touching each other and reply button is not visible clearly.

## To Reproduce

1. Visit this [URL](https://userstory.eosdesignsystem.com/story/60e599602d674800150f759a) 
2. See the comments section

## Expected behavior

There should be space between two buttons or one should be below the other.

## Environment (please complete the following information):

- OS: Windows 10
- Browser:  Google chrome.

## Additional context

![EOS User story (1)](https://user-images.githubusercontent.com/54779517/152593669-055bcab9-1b24-42dd-bdba-1fee6a607b94.png)

**Comment by codetheorem** [comment]
I am working on this.

**Comment by cyntss** [comment]
thank you @codetheorem ! let us know when you have the PR ready for review. @sharmaaditya570191 @mharshita or @SundeepChand can review it, so feel free to assign them as reviewers

**Comment by padmajabhol** [comment]
Is this issue still open? Can I work on this?

**Comment by codetheorem** [comment]
> Is this issue still open? Can I work on this?

This issue is solved
