### ISSUE TITLE
Remove unwanted scroll & pattern icon is broken

### ISSUE THREAD

**Issue by chinmaym07** [EOS-uiux-Solutions/user-story#132]
## Describe the bug

1. Unwanted scroll in the share popup when we try to share the story .
2. Pattern icon link is broken
3. Unwanted scroll in people who liked a story popup.

## To Reproduce

1. Go to [https://userstory.eosdesignsystem.com/story/60e6df9180886200152e34b9](https://userstory.eosdesignsystem.com/story/60e6df9180886200152e34b9)

![image](https://user-images.githubusercontent.com/44670961/155418261-82451c22-ba77-4703-9dde-15e780fa6381.png)

![image](https://user-images.githubusercontent.com/44670961/155418311-ecc5dcc4-97b6-4f48-907f-d101948af235.png)

2. Go to [https://userstory.eosdesignsystem.com/](https://userstory.eosdesignsystem.com/)

![image](https://user-images.githubusercontent.com/44670961/155419678-65d67c39-db40-4868-9339-a40c4c979476.png)

https://user-images.githubusercontent.com/44670961/155420112-8dc864c0-eca6-4f6a-8fdc-7db6948817e3.mp4

## Expected behavior

Scroll should be auto or hidden as there is no requirement of scroll.
Update the pattern icon link.

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):

- OS: Ubuntu 20.04 
- Browser: Firefox 97.1

**Comment by shrinishant** [comment]
@kbhutani0001 @cyntss @chinmaym07 I would like to work on this issue and solve it.
