### ISSUE TITLE
[Feature] Add toast notifications for actions

### ISSUE THREAD

**Issue by kailash360** [EOS-uiux-Solutions/user-story#135]
## Is your feature request related to a problem? Please describe.

Currently, in the application, we do not have any toast notifications for the features. When the user performs an important action, like creating a story, or editing it, there is no confirmation message generated about it. 

## Describe the solution you'd like

It would be better to add messages of whether an action was successful or not. This can be done using `react-toastify` or `react-hot-toast` packages.

## Additional context

This would make the application more interactive.

**Comment by kailash360** [comment]
@sharmaaditya570191 @cyntss 
I want to work on this

**Comment by cyntss** [comment]
I love this idea @kailash360 !
