### ISSUE TITLE
Profile image (with error) floating on the home page

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/user-story#138]
## To Reproduce

1. Go to the home page and see the following image for an inexistent profile image:

![image](https://user-images.githubusercontent.com/5013096/155711095-c2549295-35c9-4c5b-adc1-38cffb5de782.png)

## Expected behavior

That "profile" image should not appear there.

**Comment by kailash360** [comment]
@cyntss 
Can I work on this?

**Comment by cyntss** [comment]
@kailash360 yes please!

**Comment by kailash360** [comment]
@cyntss 

The loader is also broken.

![image](https://user-images.githubusercontent.com/75155230/155715247-a2572062-a36a-4efc-9f20-076c6760547d.png)


Should I fix it in this issue itself, or should I create a new issue?

**Comment by kailash360** [comment]
@cyntss 

I have created PR #139 for this issue.
