### ISSUE TITLE
[Bug] Excess spacing in filters of story list

### ISSUE THREAD

**Issue by kailash360** [EOS-uiux-Solutions/user-story#149]
## Describe the bug

Currently, there is extra spacing between the elements in the filers of story list.
![image](https://user-images.githubusercontent.com/75155230/156243535-cb490a23-9d5f-4b2e-b209-f4e5e04f3fbb.png)

## To Reproduce

1. Open [userstory.eosdesignsystem.com](https://userstory.eosdesignsystem.com/)
2. Scroll down to story list
3. There is extra spacing in elements of filter

## Expected behavior

The elements should be properly spaced such that the UI looks better. 
The proper view should be:
![image](https://user-images.githubusercontent.com/75155230/156243462-bcddb286-4bed-4f78-b8d1-a159c062f605.png)

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Chrome

**Comment by kailash360** [comment]
@cyntss @mharshita 
I want to work on this issue.

**Comment by mharshita** [comment]
Duplicate issue as #131
