### ISSUE TITLE
Update Copyright year

### ISSUE THREAD

**Issue by StarTrooper08** [EOS-uiux-Solutions/user-story#166]
## Describe the bug
![eos6](https://user-images.githubusercontent.com/72031540/157967142-363c34c2-ae51-4ba1-b858-d8c5eb6e89d6.png)

We just need to change the copyright year from 2020 to 2022 which is written on the sign-up card.

**Comment by StarTrooper08** [comment]
If it is a valid issue can I work on this issue?

**Comment by StarTrooper08** [comment]
Yep sure you can work on this issue cause it is still open.
But before that please confirm on slack whether the issue is valid .
Cause I have observed many organizations and Inc update their copyright year.


Example: Github
<img  src="https://user-images.githubusercontent.com/72031540/158519233-627e7dfe-9a9c-4886-8194-ac67b56aaa2e.png"/>

**Comment by dikshashukla455** [comment]
I have fixed this issue and made a Pull Request. Kindly review it.
