### ISSUE TITLE
Error message not removed

### ISSUE THREAD

**Issue by codetheorem** [EOS-uiux-Solutions/user-story#170]
## Describe the bug

If there is a error on the login page or register page it does not get removed if we navigate to a different page.

## To Reproduce

1. Visit the login page.
2. Try to login incorrectly by entering the wrong password.
3. Visit the register page
4. You will see the error message still there.

## Expected behavior

The error message should get removed.

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Google chrome

## Additional context

You can see here also-

https://watch.screencastify.com/v/fRHxNBBm9prAcQRvDjOV

**Comment by dikshashukla455** [comment]
Greetings
Can I work on this issue?

**Comment by codetheorem** [comment]
> Greetings
> Can I work on this issue?

There is already a PR for this.
