### ISSUE TITLE
MISALIGNED ATTACHMENT ICON IN THE VIEW STORY PAGE 

### ISSUE THREAD

**Issue by reachaadrika** [EOS-uiux-Solutions/user-story#179]
## Describe the bug

When you click on the story , for the view story page , the "attachment" icon in "Adding a comment" placeholder is misaligned , it needs to be centralized so that it doesn't look visually absurd.

## To Reproduce

1. Create A New Story
2. Click on the Story You Have Created 
3. Check the Adding a  Comment  Placeholder 
4. See the Alignment of " Attachment Icon" as marked in the image below

## Expected behavior

The Attachment Icon should be placed in the center .

## Logs

![MS Paint Microsoft Paint Online](https://user-images.githubusercontent.com/64789514/158660745-ad67e151-5076-4e66-a240-4f8dd06bcc16.png)

## Environment (please complete the following information):

- OS: WINDOWS 11
- Browser: MOZILLA FIREFOX

**Comment by mharshita** [comment]
It was designed this way so that it always stays at the bottom.
<img width="1440" alt="Screenshot 2022-03-16 at 11 58 06 PM" src="https://user-images.githubusercontent.com/60281688/158661726-183e24cd-014a-4ba0-bf6d-b127f83e697d.png">

**Comment by reachaadrika** [comment]
Okay Sure , I will be closing this issue .
