### ISSUE TITLE
Slack is not working

### ISSUE THREAD

**Issue by Arnav2001** [EOS-uiux-Solutions/user-story#306]
I want to contribute to this repository, need some assistance. kindly update slack link, so that I can communicate.

**Comment by kunal00000** [comment]
Try joining this eos-community.slack.com .

**Comment by Arnav2001** [comment]
![slack_error](https://user-images.githubusercontent.com/68494838/218316343-215a5c83-9c2b-457c-b88f-84bb3b7cf021.jpeg)

It is showing me this kindly make it public so that I can enter.

**Comment by kunal00000** [comment]
Okay, give your mail I'll send you invite.

**Comment by Arnav2001** [comment]
arnavkul07@gmail.com
