### ISSUE TITLE
UI not responsive for smaller Screen sizes 

### ISSUE THREAD

**Issue by Abhijay007** [EOS-uiux-Solutions/user-story#55]
## Describe the bug

UI is not responsive for smaller screen sizes 

## To Reproduce

1. Open application chrome
2. Use chrome inspect element to checkout responsiveness
3. Switch between screens sizes. 

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Chrome

**Additional context (OPTIONAL)**

Screenshot 1          |  Screenshot 2             |  Screenshot 3            |  Screenshot 4     
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|
![ui 1](https://user-images.githubusercontent.com/64387054/126074987-2ecc5a60-5500-4cb6-b2d0-1fb7a8df3545.PNG)|![ui 2](https://user-images.githubusercontent.com/64387054/126074994-53e4e0a5-13f3-4ef6-a4ac-9c7bceaa38df.PNG)|![ui3](https://user-images.githubusercontent.com/64387054/126075004-dee098f5-f1b6-4d51-ad03-511ac2057af1.PNG)|![ui 4](https://user-images.githubusercontent.com/64387054/126075006-85631eb9-5049-4614-83f7-7ef1d2abf7ad.PNG)

**Comment by sharmaaditya570191** [comment]
@cyntss can you help with designs for mobile?

**Comment by AsavariA** [comment]
@sharmaaditya570191 Can I try my hand at this making the application mobile responsive?

**Comment by sharmaaditya570191** [comment]
Hi @AsavariA. Welcome to EOS. The designs for the mobile screens are not ready yet. Before making major changes to code we would love to have a design. Would you like to make a design for the same? @cyntss can then help to review the design.

**Comment by AsavariA** [comment]
@sharmaaditya570191 sure

**Comment by sharmaaditya570191** [comment]
Please feel free to join us on slack - https://eos-community.slack.com

**Comment by AsavariA** [comment]
@sharmaaditya570191 @cyntss Can you please review these layouts for smaller device sizes?

https://drive.google.com/drive/folders/1lXlzxUgv6BDE4E9hoWFmgVedyZv-0hKR?usp=sharing

**Comment by sharmaaditya570191** [comment]
Nice work. Did you try out a design in Figma or Adobe XD? 

1. I think the timeline of `Under Consideration -> Implementing...Deployed` can be changed to a dropdown named `Status` for small screen sizes which displays all statuses on clicking.

Feel free to open a PR
