### ISSUE TITLE
Fix text overflow in story card in New Story page

### ISSUE THREAD

**Issue by SundeepChand** [EOS-uiux-Solutions/user-story#60]
When the search results are displayed, text overflows the displayed results. See image below

![fix-new-story-ui](https://user-images.githubusercontent.com/34120932/126330107-f25537e2-13d6-4001-9833-e9c42d4cbf8c.JPG)

**Comment by sharmaaditya570191** [comment]
We are only showing the story titles there previously. Lets keep it like that @SundeepChand .
