### ISSUE TITLE
Add PR template in repo 

### ISSUE THREAD

**Issue by Abhijay007** [EOS-uiux-Solutions/user-story#69]
## Is your feature request related to a problem? Please describe.

add issue template for raising issues related to bug reports and feature request

## Describe the solution you'd like

Add PR template in the repo so whenever a contributor open a PR he/she will provide all relevant information about that using temple 

Add PR template to the GitHub folder

**Comment by Abhijay007** [comment]
can I work on this issue?

**Comment by sharmaaditya570191** [comment]
Sure.
