### ISSUE TITLE
Instead of disabling the vote button, clicking on vote button should take you to login page, if the user is not logged in.

### ISSUE THREAD

**Issue by tushar5526** [EOS-uiux-Solutions/user-story#82]
## Is your feature request related to a problem? Please describe.

When I first visited the homepage, like most websites I thought the `vote` would be a button that I can click to upvote a story. After fiddling around I realised I had to create an account first.

## Describe the solution you'd like

It would give a better UX if the vote buttons are active even when the user is not logged in. If a user is not logged in he will be prompted to log in first or a new user can create an account.

Redirect to login page if a user is not logged in and clicks on the vote button.

## Additional context

I would like to work on it.

**Comment by cyntss** [comment]
I like this idea! I didn't realize before but it is true, the button doesn't behave like a real button when the user is logged out.

**Comment by tushar5526** [comment]
@cyntss  Should I go ahead and implement this, or wait for others to share their views?

**Comment by shrinishant** [comment]
@cyntss I would like to work on and fix this issue. Could you please assign this to me?
