### ISSUE TITLE
Mentioned usernames not converted into links

### ISSUE THREAD

**Issue by mharshita** [EOS-uiux-Solutions/user-story#88]
## Describe the bug

Currently when we mention a user in the comments section, the mentioned username comes as plain text.

## Expected behavior

Mentioned username should be a link to the profile of that user.

**Comment by kailash360** [comment]
@mharshita 
Can I work on this issue?

**Comment by mharshita** [comment]
sure

**Comment by kailash360** [comment]
It would be helpful if you can review this pending PR #104 once, so that I can start working on this issue.

**Comment by mharshita** [comment]
@kailash360  can you please see [this.](https://github.com/EOS-uiux-Solutions/user-story/pull/104#issuecomment-991947906)

**Comment by kailash360** [comment]
@mharshita can you kindly review PR #108 so that I can start working on this issue?

**Comment by kailash360** [comment]
@mharshita 
I have created PR #127 for this issue.
