### ISSUE TITLE
Relative time(posted ago) in comments metadata can't be read easily

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/user-story#94]
Issue originally posted by @arjungarg07

---

Currently, we are displaying relative time in the comment section in the format `2020-10-13 14:48:25`. 

![image](https://user-images.githubusercontent.com/5013096/137326867-ea293c6f-8e3d-463d-a0ca-27ef91cebd1f.png)

It would be better to change it to a format like `Jan 27 at 17:08` or `3 months ago` for a better user experience.

**Comment by ayushsatyam146** [comment]
Created a PR #106  changing date format to '3 months ago' format. Please review.
Thanks!
