### ISSUE TITLE
Old logo is used on small screens

### ISSUE THREAD

**Issue by cyntss** [EOS-uiux-Solutions/user-story#95]
Issue originally posted by @deutranium

---

The small screens still have the old EOS logo. It would be better to update it with the new one for consistency throughout the app

![image](https://user-images.githubusercontent.com/5013096/137327280-5d2fbe49-ab94-4e96-ba5d-4de695ae7f37.png)

**Comment by kailash360** [comment]
@cyntss, can I work on this issue?

**Comment by cyntss** [comment]
@kailash360 yes of course!

**Comment by kailash360** [comment]
@cyntss, I have created PR #100 for this issue.
Apart from this, I must say that the package is really wonderful.
